### ISSUE TITLE
Compiling problem with the ember plugin

### ISSUE THREAD

**Issue by Damianofds** [slms4redd/admin-interface#71]
Problems with the ember plugin compiling the project on windows see log below.
Since the layer.json management UI is not ready yet the ember plugin is temporary commented out.

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\work\\code\\admin-interface\\src\\main\\javascript\\node\\node',
1 verbose cli   'D:\\work\\code\\admin-interface\\src\\main\\javascript\\node\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--color=false' ]
2 info using npm@2.6.1
3 info using node@v0.12.0
4 verbose node symlink D:\work\code\admin-interface\src\main\javascript\node\node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild portal-admin-interface@0.0.0
7 info build portal-admin-interface@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info portal-admin-interface@0.0.0 Failed to exec build script
10 verbose stack Error: portal-admin-interface@0.0.0 build: `ember build`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (D:\work\code\admin-interface\src\main\javascript\node\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (D:\work\code\admin-interface\src\main\javascript\node\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid portal-admin-interface@0.0.0
12 verbose cwd D:\work\code\admin-interface\src\main\javascript
13 error Windows_NT 6.1.7601
14 error argv "D:\\work\\code\\admin-interface\\src\\main\\javascript\\node\\node" "D:\\work\\code\\admin-interface\\src\\main\\javascript\\node\\npm\\bin\\npm-cli.js" "run" "build" "--color=false"
15 error node v0.12.0
16 error npm  v2.6.1
17 error code ELIFECYCLE
18 error portal-admin-interface@0.0.0 build: `ember build`
18 error Exit status 1
19 error Failed at the portal-admin-interface@0.0.0 build script 'ember build'.
19 error This is most likely a problem with the portal-admin-interface package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     ember build
19 error You can get their info via:
19 error     npm owner ls portal-admin-interface
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by Damianofds** [comment]
See also https://github.com/slms4redd/admin-interface/commit/12986f2d64bc8bec96776a6c41a38d5484d61ea0

**Comment by Damianofds** [comment]
ember plugin has been removed since the layer.json UI is going to be developed with another approach
